config/routes.rb
#
#

#------------------------------------------------------------------------------
Rails.application.routes.draw do
  resources :lists

  root :to => 'home#index'

  match 'activities' => 'home#index'
  match 'admin'      => 'admin/users#index',       :as => :admin
  match 'login'      => 'authentications#new',     :as => :login
  match 'logout'     => 'authentications#destroy', :as => :logout
  match 'profile'    => 'users#show',              :as => :profile
  match 'signup'     => 'users#new',               :as => :signup

  match '/home/options',  :as => :options
  match '/home/toggle',   :as => :toggle
  match '/home/timeline', :as => :timeline
  match '/home/timezone', :as => :timezone
  match '/home/redraw',   :as => :redraw

  resource  :authentication, :except => [:index, :edit]
  resources :comments,       :except => [:new, :show]
  resources :emails,         :only   => [:destroy]
  resources :passwords,      :only   => [:new, :create, :edit, :update]

  resources :accounts, :id => /\d+/ do
    collection do
      get  :advanced_search
      post :filter
      get  :options
      get  :field_group
      match :auto_complete
      get  :redraw
      get  :versions
    end
    member do
      put  :attach
      post :discard
      post :subscribe
      post :unsubscribe
      get  :opportunities
    end
  end

  resources :campaigns, :id => /\d+/ do
    collection do
      get  :advanced_search
      post :filter
      get  :options
      get  :field_group
      match :auto_complete
      get  :redraw
      get  :versions
    end
    member do
      put  :attach
      post :discard
      post :subscribe
      post :unsubscribe
      get  :leads
      get  :opportunities
    end
  end


  resources :leads, :id => /\d+/ do
    collection do
      get  :advanced_search
      post :filter
      get  :options
      get  :field_group
      match :auto_complete
      get  :redraw
      get  :versions
      get  :autocomplete_account_name
    end
    member do
      get  :convert
      post :discard
      post :subscribe
      post :unsubscribe
      put  :attach
      put  :promote
      put  :reject
    end
  end

  resources :opportunities, :id => /\d+/ do
    collection do
      get  :advanced_search
      post :filter
      get  :options
      get  :field_group
      match :auto_complete
      get  :redraw
      get  :versions
    end
    member do
      put  :attach
      post :discard
      post :subscribe
      post :unsubscribe
    end
  end

  resources :tasks, :id => /\d+/ do
    collection do
      post :filter
      match :auto_complete
    end
    member do
      put  :complete
      put  :uncomplete
    end
  end

  resources :users, :id => /\d+/, :except => [:index, :destroy] do
    member do
      get  :avatar
      get  :password
      put  :upload_avatar
      put  :change_password
      post :redraw
    end
    collection do
      get  :opportunities_overview
      match :auto_complete
    end
  end

  namespace :admin do
    resources :groups

    resources :users do
      collection do
        match :auto_complete
      end
      member do
        get :confirm
        put :suspend
        put :reactivate
      end
    end

    resources :field_groups, :except => [:index, :show] do
      collection do
        post :sort
      end
      member do
        get :confirm
      end
    end

    resources :fields do
      collection do
        match :auto_complete
        get   :options
        get   :redraw
        post  :sort
        get   :subform
      end
    end

    resources :tags, :except => [:show] do
      member do
        get :confirm
      end
    end

    resources :fields, :as => :custom_fields
    resources :fields, :as => :core_fields

    resources :settings, :only => :index
    resources :plugins,  :only => :index
  end

end

app/models/users/ability.rb
#
#

#------------------------------------------------------------------------------
# See the wiki for details: https://github.com/ryanb/cancan/wiki/Defining-Abilities

class Ability
  include CanCan::Ability

  def initialize(user)

    # handle signup
    can(:create, User) if User.can_signup?

    if user.present?
      entities = [Account, Lead, Opportunity]

      # User
      can :manage, User, id: user.id # can do any action on themselves


      # Entities
      can :manage, entities, :access => 'Public'
      can :manage, entities , :user_id => user.id
      can :manage, entities , :assigned_to => user.id

      #
      # Due to an obscure bug (see https://github.com/ryanb/cancan/issues/213)
      # we must switch on user.admin? here to avoid the nil constraints which
      # activate the issue referred to above.
      #
      if user.admin?
        can :manage, :all
      else
        # Group or User permissions
        t = Permission.arel_table
        scope = t[:user_id].eq(user.id)

        if (group_ids = user.group_ids).any?
          scope = scope.or(t[:group_id].eq_any(group_ids))
        end

        entities.each do |klass|
          if (asset_ids = Permission.where(scope.and(t[:asset_type].eq(klass.name))).value_of(:asset_id)).any?
            can :manage, klass, :id => asset_ids
          end
        end
      end # if user.admin?

    end
  end

  ActiveSupport.run_load_hooks(:fat_free_crm_ability, self)
end

app/models/users/group.rb
#
#

#------------------------------------------------------------------------------
class Group < ActiveRecord::Base
  has_and_belongs_to_many :users
  has_many :permissions

  attr_accessible :name, :user_ids

  validates :name, :presence => true, :uniqueness => true

  ActiveSupport.run_load_hooks(:fat_free_crm_group, self)
end

app/models/users/permission.rb
#
#

#------------------------------------------------------------------------------
# == Schema Information
#
# Table name: permissions
#
#  id         :integer         not null, primary key
#  user_id    :integer
#  asset_id   :integer
#  asset_type :string(255)
#  created_at :datetime
#  updated_at :datetime
#

class Permission < ActiveRecord::Base
  belongs_to :user
  belongs_to :group
  belongs_to :asset, :polymorphic => true

  validates_presence_of :user_id, :unless => :group_id?
  validates_presence_of :group_id, :unless => :user_id?

  ActiveSupport.run_load_hooks(:fat_free_crm_permission, self)
end

app/controllers/admin/users_controller.rb
#
#

#------------------------------------------------------------------------------
class Admin::UsersController < Admin::ApplicationController
  before_filter "set_current_tab('admin/users')", :only => [ :index, :show ]

  load_resource :except => [:create]

  # GET /admin/users
  # GET /admin/users.xml                                                   HTML
  #----------------------------------------------------------------------------
  def index
    @users = get_users(:page => params[:page])
    respond_with(@users)
  end

  # GET /admin/users/1
  # GET /admin/users/1.xml
  #----------------------------------------------------------------------------
  def show
    respond_with(@user)
  end

  # GET /admin/users/new
  # GET /admin/users/new.xml                                               AJAX
  #----------------------------------------------------------------------------
  def new
    respond_with(@user)
  end

  # GET /admin/users/1/edit                                                AJAX
  #----------------------------------------------------------------------------
  def edit
    if params[:previous].to_s =~ /(\d+)\z/
      @previous = User.find_by_id($1) || $1.to_i
    end

    respond_with(@user)
  end

  # POST /admin/users
  # POST /admin/users.xml                                                  AJAX
  #----------------------------------------------------------------------------
  def create
    params[:user][:password_confirmation] = nil if params[:user][:password_confirmation].blank?
    admin = params[:user].delete(:admin)
    @user = User.new(params[:user])
    @user.admin = (admin == "1") unless admin.nil?
    @user.save_without_session_maintenance

    respond_with(@user)
  end

  # PUT /admin/users/1
  # PUT /admin/users/1.xml                                                 AJAX
  #----------------------------------------------------------------------------
  def update
    params[:user][:password_confirmation] = nil if params[:user][:password_confirmation].blank?
    admin = params[:user].delete(:admin)
    @user = User.find(params[:id])
    @user.attributes = params[:user]
    @user.admin = (admin == "1") unless admin.nil?
    @user.save_without_session_maintenance

    respond_with(@user)
  end

  # GET /admin/users/1/confirm                                             AJAX
  #----------------------------------------------------------------------------
  def confirm
    respond_with(@user)
  end

  # DELETE /admin/users/1
  # DELETE /admin/users/1.xml                                              AJAX
  #----------------------------------------------------------------------------
  def destroy
    flash[:warning] = t(:msg_cant_delete_user, @user.full_name) unless @user.destroy

    respond_with(@user)
  end

  # POST /users/auto_complete/query                                        AJAX
  #----------------------------------------------------------------------------
  # Handled by Admin::ApplicationController :auto_complete

  # PUT /admin/users/1/suspend
  # PUT /admin/users/1/suspend.xml                                         AJAX
  #----------------------------------------------------------------------------
  def suspend
    @user.update_attribute(:suspended_at, Time.now) if @user != current_user

    respond_with(@user)
  end

  # PUT /admin/users/1/reactivate
  # PUT /admin/users/1/reactivate.xml                                      AJAX
  #----------------------------------------------------------------------------
  def reactivate
    @user.update_attribute(:suspended_at, nil)

    respond_with(@user)
  end

private

  #----------------------------------------------------------------------------
  def get_users(options = {})
    self.current_page  = options[:page] if options[:page]
    self.current_query = params[:query] if params[:query]

    @search = klass.search(params[:q])
    @search.build_grouping unless @search.groupings.any?

    wants = request.format
    scope = User.by_id
    scope = scope.merge(@search.result)
    scope = scope.text_search(current_query)      if current_query.present?
    scope = scope.paginate(:page => current_page) if wants.html? || wants.js? || wants.xml?
    scope
  end
end

app/controllers/users_controller.rb
#
#

#------------------------------------------------------------------------------
class UsersController < ApplicationController

  before_filter :set_current_tab, :only => [ :show, :active ] # Don't hightlight any tabs.

  check_authorization
  load_and_authorize_resource # handles all security

  respond_to :html, :only => [ :show, :new ]

  # GET /users/1
  # GET /users/1.js
  #----------------------------------------------------------------------------
  def show
    @user = current_user if params[:id].nil?
    respond_with(@user)
  end

  # GET /users/new
  # GET /users/new.js
  #----------------------------------------------------------------------------
  def new
    respond_with(@user)
  end

  # POST /users
  # POST /users.js
  #----------------------------------------------------------------------------
  def create
    if @user.save
      if Setting.user_signup == :needs_approval
        flash[:notice] = t(:msg_account_created)
        redirect_to login_url
      else
        flash[:notice] = t(:msg_successful_signup)
        redirect_back_or_default profile_url
      end
    else
      render :new
    end
  end

  # GET /users/1/edit.js
  #----------------------------------------------------------------------------
  def edit
    respond_with(@user)
  end

  # PUT /users/1
  # PUT /users/1.js
  #----------------------------------------------------------------------------
  def update
    @user.update_attributes(params[:user])
    respond_with(@user)
  end

  # GET /users/1/avatar
  # GET /users/1/avatar.js
  #----------------------------------------------------------------------------
  def avatar
    respond_with(@user)
  end

  # PUT /users/1/upload_avatar
  # PUT /users/1/upload_avatar.js
  #----------------------------------------------------------------------------
  def upload_avatar
    if params[:gravatar]
      @user.avatar = nil
      @user.save
      render
    else
      if params[:avatar]
        avatar = Avatar.create(params[:avatar].merge(:entity => @user))
        if avatar.valid?
          @user.avatar = avatar
        else
          @user.avatar.errors.clear
          @user.avatar.errors.add(:image, t(:msg_bad_image_file))
        end
      end
      responds_to_parent do
        # Without return RSpec2 screams bloody murder about rendering twice:
        # within the block and after yield in responds_to_parent.
        render and (return if Rails.env.test?)
      end
    end
  end

  # GET /users/1/password
  # GET /users/1/password.js
  #----------------------------------------------------------------------------
  def password
    respond_with(@user)
  end

  # PUT /users/1/change_password
  # PUT /users/1/change_password.js
  #----------------------------------------------------------------------------
  def change_password
    if @user.valid_password?(params[:current_password], true) || @user.password_hash.blank?
      unless params[:user][:password].blank?
        @user.password = params[:user][:password]
        @user.password_confirmation = params[:user][:password_confirmation]
        @user.save
        flash[:notice] = t(:msg_password_changed)
      else
        flash[:notice] = t(:msg_password_not_changed)
      end
    else
      @user.errors.add(:current_password, t(:msg_invalid_password))
    end

    respond_with(@user)
  end

  # GET /users/1/redraw
  #----------------------------------------------------------------------------
  def redraw
    current_user.preference[:locale] = params[:locale]
    render :js => %Q{window.location.href = "#{user_path(current_user)}";}
  end

  # GET /users/opportunities_overview
  #----------------------------------------------------------------------------
  # def opportunities_overview
  #   @users_with_opportunities = User.have_assigned_opportunities.order(:first_name)
  #   @unassigned_opportunities = Opportunity.my.unassigned.pipeline.order(:stage)
  # end

end

app/helpers/admin/users_helper.rb
#
#

#------------------------------------------------------------------------------
module Admin::UsersHelper

  def link_to_suspend(user)
    link_to(t(:suspend) + "!", suspend_admin_user_path(user), :method => :put, :remote => true)
  end

  #----------------------------------------------------------------------------
  def link_to_reactivate(user)
    name = user.awaits_approval? ? t(:approve) + "!" : t(:reactivate) + "!"
    link_to(name, reactivate_admin_user_path(user), :method => :put, :remote => true)
  end

  #----------------------------------------------------------------------------
  def link_to_confirm(user)
    link_to(t(:delete) + "?", confirm_admin_user_path(user), :method => :get, :remote => true)
  end

  # User summary info for RSS/ATOM feeds.
  #----------------------------------------------------------------------------
  def user_summary(user)
    summary = []
    title_and_company = user.title.blank? ? '' : h(user.title)
    title_and_company << " #{t(:at)} #{user.company}" unless user.company.blank?
    summary << title_and_company unless title_and_company.blank?
    summary << t('pluralize.login', user.login_count) if user.last_request_at && user.login_count > 0
    summary << user.email
    summary << "#{t :phone_small}: #{user.phone}" unless user.phone.blank?
    summary << "#{t :mobile_small}: #{user.mobile}" unless user.mobile.blank?
    summary << if !user.suspended?
      t(:user_since, l(user.created_at.to_date, :format => :mmddyy))
    elsif user.awaits_approval?
      t(:user_signed_up_on, l(user.created_at, :format => :mmddhhss))
    else
      t(:user_suspended_on, l(user.created_at.to_date, :format => :mmddyy))
    end
    summary << if user.awaits_approval?
      t(:user_signed_up)
    elsif user.suspended?
      t(:user_suspended)
    elsif user.admin?
      t(:user_admin)
    else
      t(:user_active)
    end
    summary.join(', ')
  end
end

app/helpers/users_helper.rb
#
#

#------------------------------------------------------------------------------
module UsersHelper

  def language_for(user)
    if user.preference[:locale]
      locale, language = languages.detect{ |locale, language| locale == user.preference[:locale] }
    end
    language || "English"
  end

  def sort_by_language
    languages.sort.map do |locale, language|
      %Q[{ name: "#{language}", on_select: function() { #{redraw(:locale, [ locale, language ], url_for(:action => :redraw, :id => current_user))} } }]
    end
  end

  def all_users
    User.by_name
  end

  def user_select(asset, users, myself)
    user_options = user_options_for_select(users, myself)
    select(asset, :assigned_to, user_options,
           { :include_blank => t(:unassigned) },
           { :style         => "width:160px",
             :class => 'select2'              })
  end

  def user_options_for_select(users, myself)
    (users - [myself]).map{|u| [u.full_name, u.id]}.prepend([t(:myself), myself.id])
  end
end

app/views/admin/users/_confirm.html.haml
.confirm[@user, :confirm]
  #{t :user_confirm_delete}
  #{t :delete} <b>#{@user.full_name}</b>?
  = link_to_confirm_delete(@user) << " : "
  = link_to_function(t(:no_button), "crm.flick('#{dom_id(@user, :confirm)}', 'remove')")

app/views/admin/users/_new.html.haml
= form_for([:admin, @user], :html => one_submit_only.merge({:autocomplete => 'off'}), :remote => true) do |f|
  = link_to_close new_admin_user_path

  = f.error_messages :object_name => t('user')

  = render "admin/users/profile", :f => f
  .buttonbar
    = f.submit t(:create_user)
    #{t :or}
    = link_to_cancel new_admin_user_path

app/views/admin/users/_sidebar_index.html.haml
.filters#filters
  = render "shared/search"

app/views/admin/users/_user.html.haml
%li.highlight[user]

  - if user.awaits_approval?
    .strip.signed_up #{t :user_signed_up}
  - elsif user.suspended?
    .strip.suspended #{t :user_suspended}
  - elsif user.admin?
    .strip.admin #{t :user_admin}
  - else
    .strip.active #{t :user_active}

  = avatar_for(user, :size => :medium, :width => 30, :height => 30 )

  .indentfull
    .tools
      = link_to_edit(user, :url => edit_admin_user_path(user)) << " | "

      - if user.suspended?
        = link_to_reactivate(user) << " | "
      - elsif user != current_user
        = link_to_suspend(user) << " | "
      - else
        %span.grayed #{t :suspend}!
        = " | "

      - if user != current_user
        = link_to_confirm(user)
      - else
        %span.grayed #{t :delete}?

    %span.black #{link_to( user.full_name, user)} (#{user.username})
    %tt
      = "- #{user.title}" unless user.title.blank?
      = " " + t(:at) + " " + user.company unless user.company.blank?

      %span.black= "|"
      - if user.last_request_at && user.login_count > 0
        = t('pluralize.login', user.login_count)
        %span.black= "|"

      - if user.awaits_approval?
        %b.cool #{t :user_awaits_approval}
      - elsif user.last_request_at
        %span.cool= t(:last_seen2, timeago(user.last_request_at)).html_safe
      - else
        %span.warn #{t :user_never_logged_in}
    %dt{ :style => "padding: 2px 0px 0px 0px" }
      = link_to_email(user.email.to_s) << " | "
      - if user.phone?
        = t(:phone_small) << ":"
        = content_tag(:b, user.phone) << " | "
      - if user.mobile?
        = t(:mobile_small) << ":"
        = content_tag(:b, user.mobile) << " | "

      - if !user.suspended?
        %span #{t(:user_since, l(user.created_at.to_date, :format => :mmddyy))}
      - elsif user.awaits_approval?
        %b.cool #{t(:user_signed_up_on, l(user.created_at, :format => :mmddhhss))}
      - else
        %span.warn #{t(:user_suspended_on, l(user.created_at.to_date, :format => :mmddyy))}
    - groups = user.groups
    - unless groups.count.zero?
      %dt{ :style => "padding: 2px 0px 0px 0px" }
        = t(:groups) << ":"
        = groups.map(&:name).join(', ')

app/views/admin/users/confirm.js.haml
- id = dom_id(@user, :confirm)

if ($('##{id}').size() > 0) {
crm.flick('#{id}', 'remove');
} else {
$('##{dom_id(@user)}').prepend('#{ j (render :partial => "confirm") }');
}

app/views/admin/users/destroy.js.haml
- id = dom_id(@user)

- if @user.destroyed?
  $('##{id}').css('background-color', '#ffe4e1').slideUp(250).remove();
- else
  crm.flick('#{dom_id(@user, :confirm)}', 'remove');
  $('##{id}').effect('shake', { duration:250, distance: 6 });
  $('#flash').html('#{j flash[:warning]}');
  crm.flash('warning');
  - flash[:warning] = nil

app/views/admin/users/edit.js.haml
- id = dom_id(@user)

- if params[:cancel].true?     # <----------------- Hide [Edit User]
  $('##{id}').replaceWith('#{ j render(:partial => "user", :collection => [ @user ]) }');

- else # <----------------------------------------  Show [Edit User] form.

  - if @previous                                    # Hide open [Edit User] form if any.
    - if @previous.is_a?(User)                      # Previous user still exists?
      $('##{dom_id(@previous)}').replaceWith('#{ j render(:partial => "user", :collection => [ @previous ]) }');
    - else
      crm.flick('user_#{@previous}', 'remove');

  -# Disable onMouseOver for the list item.
  -# Hide [Create User] form if any.
  -# Show [Edit User] form.
  crm.highlight_off('#{id}');
  crm.hide_form('create_user');
  $('##{id}').html('#{ j render(:partial => "edit") }');
  $('#user_username').focus();

app/views/admin/users/index.html.haml
= styles_for :user

.title_tools
  = link_to_inline(:create_user, new_admin_user_path, :text => t(:create_user))

.title
  %span#create_user_title #{t :users}
  = image_tag("loading.gif", :size => :thumb, :id => "loading", :style => "display: none;")
.remote#create_user{ hidden }

.list#users= render :partial => "admin/users/user", :collection => @users

app/views/admin/users/index.js.haml
$('#users').html('#{ j render(:partial => "admin/users/user", :collection => @users) }');
$('#paginate').html('#{ j render(:partial => "shared/paginate") }')

app/views/admin/users/new.js.haml
crm.flip_form('create_user');

- unless params[:cancel].true?
  $('#create_user').html('#{ j render(:partial => "new") }');
  $('#empty').html('');
  crm.set_title('create_user', '#{t(:create_user)}');

- else
  crm.set_title('create_user', '#{t(:users)}');

app/views/admin/users/reactivate.js.haml
- id = dom_id(@user)
$('##{id}').replaceWith('#{ j render(:partial => "user", :collection => [ @user ]) }');
$('##{id}').effect("highlight", { duration:1000 });

app/views/admin/users/show.html.haml
.title= h(@user.full_name)
%p
:erb
  <%= link_to t(:edit), edit_admin_user_path(@user) %> |
  <%= link_to t(:back), admin_users_path %>

app/views/admin/users/suspend.js.haml
- id = dom_id(@user)
$('##{id}').replaceWith('#{ j render(:partial => "user", :collection => [ @user ]) }');
$('##{id}').effect("highlight", { duration:1000 });

app/views/admin/users/update.js.haml
- id = dom_id(@user)

- if @user.errors.empty?
  $('##{id}').replaceWith('#{ j render(:partial => "user", :collection => [ @user ]) }')
  $('##{id}').effect("highlight", { duration:1000 });
- else
  $('##{id}').html('#{j render(:partial => "edit") }')
  $('##{id}').effect("shake", { duration:250, distance: 6 });
  $('#user_username').focus()